[package]
name = "lan-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
tokio-tungstenite = "0.27.0"
tungstenite = "0.27.0"
futures = "0.3"
mdns = "3.0.0"
anyhow = "1.0.98"
uuid = { version = "1.17.0", features = ["v4"] }
whoami = "1.6.0"
